@echo off
echo Eliminando base de datos...
del /q db.sqlite3
echo Eliminando migraciones...
rmdir /s /q core\migrations
echo Creando carpeta de migraciones...
mkdir core\migrations
echo. > core\migrations\__init__.py
echo Eliminando archivos subidos...
rmdir /s /q media
echo Creando carpetas de media...
mkdir media
mkdir media\documentos
mkdir media\documentos\cedulas
mkdir media\documentos\residencia
echo Generando nuevas migraciones...
python manage.py makemigrations
echo Aplicando migraciones...
python manage.py migrate
echo Creando superusuario...
python manage.py createsuperuser
echo ¡Listo! Ejecuta 'python manage.py runserver' para iniciar.
pause

REM ejecuta D:\VzlaUnida>.\reset_db.bat"