# Generated by Django 6.0.6 on 2026-06-28 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=100)),
                ('apellidos', models.CharField(default='', max_length=100)),
                ('cedula', models.CharField(default='', max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=300)),
                ('capacidad_ninos', models.IntegerField(default=0)),
                ('capacidad_adultos', models.IntegerField(default=0)),
                ('capacidad_adultos_mayores', models.IntegerField(default=0)),
                ('acepta_mascotas_pequenas', models.BooleanField(default=False)),
                ('acepta_mascotas_medianas', models.BooleanField(default=False)),
                ('acepta_mascotas_grandes', models.BooleanField(default=False)),
                ('tipo_acogida', models.CharField(choices=[('Habitacion(es)', 'Habitación(es)'), ('Anexo independiente', 'Anexo independiente'), ('Vivienda completa', 'Vivienda completa')], max_length=50)),
                ('tiempo_disponible_meses', models.IntegerField(default=1)),
                ('cedula_file', models.FileField(upload_to='documentos/cedulas/')),
                ('residencia_file', models.FileField(upload_to='documentos/residencia/')),
                ('estado_verificacion', models.CharField(default='pendiente', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
