# Generated by Django 6.0.6 on 2026-07-10 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Afectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=100)),
                ('apellidos', models.CharField(default='', max_length=100)),
                ('prefijo_cedula', models.CharField(choices=[('V', 'V'), ('E', 'E')], default='V', max_length=1)),
                ('numero_cedula', models.CharField(default='', max_length=20)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('ciudad', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(default='', max_length=100)),
                ('sector', models.CharField(default='', max_length=300)),
                ('direccion_anterior', models.TextField(default='', help_text='Dirección donde vivía antes del terremoto')),
                ('cantidad_ninos', models.IntegerField(default=0, help_text='Cantidad de niños en el núcleo familiar (menor de 18 años)')),
                ('cantidad_adultos', models.IntegerField(default=0, help_text='Cantidad de adultos en el núcleo familiar')),
                ('cantidad_adultos_mayores', models.IntegerField(default=0, help_text='Cantidad de adultos mayores en el núcleo familiar (mayor a 65 años)')),
                ('tiene_mascotas', models.BooleanField(default=False, help_text='Indica si el núcleo familiar tiene mascotas')),
                ('cedula_file', models.FileField(upload_to='documentos/cedulas_afectados/')),
                ('residencia_file', models.FileField(upload_to='documentos/residencia_afectados/')),
                ('estado_verificacion', models.CharField(choices=[('pendiente', '⏳ Pendiente de revisión'), ('en_revision', '🔍 En revisión'), ('aprobado', '✅ Aprobado'), ('rechazado', '❌ Rechazado'), ('requiere_correccion', '📝 Requiere corrección')], default='pendiente', max_length=20)),
                ('comentario_verificacion', models.TextField(blank=True, help_text='Comentario del administrador sobre la verificación', null=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, help_text='Fecha en que se realizó la verificación', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Afectado',
                'verbose_name_plural': 'Afectados',
                'unique_together': {('prefijo_cedula', 'numero_cedula')},
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=100)),
                ('apellidos', models.CharField(default='', max_length=100)),
                ('prefijo_cedula', models.CharField(choices=[('V', 'V'), ('E', 'E')], default='V', max_length=1)),
                ('numero_cedula', models.CharField(default='', max_length=20)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('ciudad', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(default='', max_length=100)),
                ('sector', models.CharField(default='', max_length=300)),
                ('cantidad_personas', models.IntegerField(default=0)),
                ('acepta_ninos', models.BooleanField(default=False)),
                ('acepta_adultos', models.BooleanField(default=False)),
                ('acepta_adultos_mayores', models.BooleanField(default=False)),
                ('acepta_mascotas', models.BooleanField(default=False)),
                ('tipo_acogida', models.CharField(choices=[('Habitacion(es)', 'Habitación(es)'), ('Anexo independiente', 'Anexo independiente'), ('Vivienda completa', 'Vivienda completa')], default='Habitacion(es)', max_length=50)),
                ('tiempo_disponible_meses', models.IntegerField(default=1)),
                ('cedula_file', models.FileField(upload_to='documentos/cedulas/')),
                ('residencia_file', models.FileField(upload_to='documentos/residencia/')),
                ('estado_verificacion', models.CharField(choices=[('pendiente', '⏳ Pendiente de revisión'), ('en_revision', '🔍 En revisión'), ('aprobado', '✅ Aprobado'), ('rechazado', '❌ Rechazado'), ('requiere_correccion', '📝 Requiere corrección')], default='pendiente', max_length=20)),
                ('comentario_verificacion', models.TextField(blank=True, help_text='Comentario del administrador sobre la verificación', null=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, help_text='Fecha en que se realizó la verificación', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Huésped',
                'verbose_name_plural': 'Huéspedes',
                'unique_together': {('prefijo_cedula', 'numero_cedula')},
            },
        ),
    ]
