# Generated by Django 6.0.6 on 2026-06-27 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afectado',
            name='necesita_asistencia',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='capacidad_personas',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='huesped',
            name='esta_verificado',
        ),
        migrations.AddField(
            model_name='afectado',
            name='documento_afectado',
            field=models.FileField(blank=True, null=True, upload_to='documentos/afectados/'),
        ),
        migrations.AddField(
            model_name='afectado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='afectado',
            name='esta_reubicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='afectado',
            name='telefono',
            field=models.CharField(default=datetime.datetime(2026, 6, 27, 23, 46, 16, 107511, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huesped',
            name='acepta_mascotas_grandes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='huesped',
            name='acepta_mascotas_medianas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='huesped',
            name='acepta_mascotas_pequenas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='huesped',
            name='capacidad_adultos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='huesped',
            name='capacidad_adultos_mayores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='huesped',
            name='capacidad_ninos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='huesped',
            name='cedula_file',
            field=models.FileField(default=datetime.datetime(2026, 6, 27, 23, 47, 20, 115213, tzinfo=datetime.timezone.utc), upload_to='documentos/cedulas/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huesped',
            name='ciudad',
            field=models.CharField(default=datetime.datetime(2026, 6, 27, 23, 47, 31, 563203, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huesped',
            name='estado',
            field=models.CharField(default=datetime.datetime(2026, 6, 27, 23, 47, 36, 859854, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huesped',
            name='estado_verificacion',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='huesped',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='huesped',
            name='residencia_file',
            field=models.FileField(default=datetime.datetime(2026, 6, 27, 23, 47, 41, 443229, tzinfo=datetime.timezone.utc), upload_to='documentos/residencia/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huesped',
            name='sector',
            field=models.CharField(default=datetime.datetime(2026, 6, 27, 23, 47, 45, 99138, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huesped',
            name='telefono',
            field=models.CharField(default=datetime.datetime(2026, 6, 27, 23, 47, 47, 59068, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huesped',
            name='tiempo_disponible_meses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='huesped',
            name='tipo_acogida',
            field=models.CharField(default=datetime.datetime(2026, 6, 27, 23, 47, 49, 331157, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huesped',
            name='verificado_manualmente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='afectado',
            name='cantidad_familiares',
            field=models.IntegerField(default=1),
        ),
    ]
