# Generated by Django 6.0.6 on 2026-06-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='estado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='sector',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='tipo_acogida',
            field=models.CharField(choices=[('Habitacion(es)', 'Habitación(es)'), ('Anexo independiente', 'Anexo independiente'), ('Vivienda completa', 'Vivienda completa')], default='Habitacion(es)', max_length=50),
        ),
    ]
