# Generated by Django 6.0.6 on 2026-06-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_huesped_ciudad_alter_huesped_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huesped',
            old_name='cedula',
            new_name='numero_cedula',
        ),
        migrations.AddField(
            model_name='afectado',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='afectado',
            name='estado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='afectado',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='huesped',
            name='prefijo_cedula',
            field=models.CharField(choices=[('V', 'V'), ('E', 'E')], default='V', max_length=1),
        ),
    ]
