# Generated by Django 6.0.6 on 2026-06-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_huesped_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afectado',
            name='cantidad_familiares',
        ),
        migrations.RemoveField(
            model_name='afectado',
            name='documento_afectado',
        ),
        migrations.RemoveField(
            model_name='afectado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='afectado',
            name='esta_reubicado',
        ),
        migrations.RemoveField(
            model_name='afectado',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='afectado',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='huesped',
            name='tipo_acogida',
            field=models.CharField(choices=[('Habitacion(es)', 'Habitación(es)'), ('Anexo independiente', 'Anexo independiente'), ('Vivienda completa', 'Vivienda completa')], max_length=50),
        ),
    ]
