# Generated by Django 6.0.6 on 2026-06-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_afectado_cantidad_familiares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='capacidad_ninos',
            field=models.IntegerField(default=0, verbose_name='Capacidad niños'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='sector',
            field=models.CharField(max_length=300),
        ),
    ]
